server:
    port: 9999

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**
      - id: USER-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**

eureka:
  instance : 
    prefer-ip-address: true
  client:
    # fetch-registry: true
    # register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

  