server:
    port: 9999

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**
      - id: USER-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**

eureka:
  instance : 
    prefer-ip-address: true
  client:
    # fetch-registry: true
    # register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
#okta configuration for API gateWay
okta:
  oauth2:
    issuer: https://dev-76877737.okta.com/oauth2/default
    audience: api://default
    client-id: 0oab1dsko2mg8zd985d7
    client-secret: mwFj65SJswKU-6H_o9_DoWhW9pmfhNye8uL1xv56VFTGhU1tDl5MmEqstg23bNTu
    scopes: openid, profile, email, offline_access  