server:
    port: 9590

spring :
    data :
        mongodb : 
            uri: mongodb://root:koot@localhost:27017/microservice?authSource=admin
    jpa:
      # ddl-auto: create-drop
        ddl-auto: update
        show-sql: true
    
