server:
    port: 9092

spring :
    data :
        mongodb : 
            uri: mongodb://root:koot@localhost:27017/microservice?authSource=admin
    jpa:
      # ddl-auto: create-drop
        ddl-auto: update
        show-sql: true
eureka:
  instance : 
    prefer-ip-address: true
  client:
    # fetch-registry: true
    # register-with-eureka: true
    serviceUrl:
        defaultZone: http://localhost:9090/eureka
    
