server:
  port: 9093
username: sa
password: sa
url: jdbc:sqlite:memory:myDb?cache=shared
logging:
  level:
    root : INFO
    
hibernate:
  hbm2ddl:
    # auto: create-drop
    auto: update
  show_sql: 'true'
driverClassName: org.sqlite.JDBC
spring:
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:9095
  # profiles:
  #   active: prod
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  

# eureka:
#   instance : 
#     prefer-ip-address: true
#   client:
#     # fetch-registry: true
#     # register-with-eureka: true
#     serviceUrl:
#       defaultZone: http://localhost:9090/eureka
      

