server:
    port: 9095

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: koot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect



